const std = @import("std");
const builtin = @import("builtin");
const protocols = @import("generated/protocols.zig");

pub var key_states = [Key.Count]Key.State;

pub const Key = enum(u32) {
    invalid = 0,
    Escape,
    @"1",
    exclam,
    @"2",
    at,
    @"3",
    numbersign,
    @"4",
    @"5",
    percent,
    @"6",
    asciicircum,
    @"7",
    ampersand,
    @"8",
    asterisk,
    @"9",
    @"0",
    minus,
    underscore,
    equal,
    plus,
    BackSpace,
    Tab,
    a,
    c,
    b,
    d,
    e,
    f,
    g,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    r,
    q,
    s,
    t,
    u,
    v,
    w,
    x,
    y,
    z,
    bracketleft,
    braceleft,
    bracketright,
    braceright,
    Return,
    Control_L,
    semicolon,
    colon,
    apostrophe,
    quotedbl,
    grave,
    asciitilde,
    Shift_L,
    backslash,
    comma,
    period,
    slash,
    question,
    Shift_R,
    KP_Multiply,
    XF86ClearGrab,

    space,
    Caps_Lock,

    F1,
    XF86Switch_VT_1,

    F2,
    XF86Switch_VT_2,

    F3,
    XF86Switch_VT_3,

    F4,
    XF86Switch_VT_4,

    F5,
    XF86Switch_VT_5,

    F6,
    XF86Switch_VT_6,

    F7,
    XF86Switch_VT_7,

    F8,
    XF86Switch_VT_8,

    F9,
    XF86Switch_VT_9,

    F10,
    XF86Switch_VT_10,

    Num_Lock,
    Scroll_Lock,
    KP_Home,
    KP_7,
    KP_Up,
    KP_8,
    KP_Prior,
    KP_9,

    KP_Subtract,

    KP_Left,
    KP_4,
    KP_Begin,
    KP_5,
    KP_Right,
    KP_6,

    KP_End,
    KP_1,
    KP_Down,
    KP_2,
    KP_Next,
    KP_3,
    KP_Insert,
    KP_0,
    KP_Delete,
    KP_Decimal,
    ISO_Level3_Shift,
    less,
    greater,
    bar,
    brokenbar,

    F11,
    XF86Switch_VT_11,

    F12,
    XF86Switch_VT_12,

    Katakana,
    Hiragana,
    Henkan_Mode,
    Hiragana_Katakana,
    Muhenkan,
    KP_Enter,
    Control_R,

    KP_Divide,
    XF86Ungrab,

    Sys_Req,

    Alt_R,
    Meta_R,
    Linefeed,
    Home,
    Up,
    Prior,
    Left,
    Right,
    End,
    Down,
    Next,
    Insert,
    Delete,
    XF86AudioMute,
    XF86AudioLowerVolume,
    XF86AudioRaiseVolume,
    XF86PowerOff,
    KP_Equal,
    plusminus,

    Pause,
    Break,

    XF86LaunchA,
    Hangul,
    Hangul_Hanja,
    Super_L,
    Super_R,
    Menu,
    SunProps,
    Undo,
    SunFront,
    XF86Copy,
    XF86Open,
    XF86Paste,
    Find,
    XF86Cut,
    Help,
    XF86MenuKB,
    XF86Calculator,
    XF86Sleep,
    XF86WakeUp,
    XF86Explorer,
    XF86Xfer,
    XF86Launch1,
    XF86Launch2,
    XF86WWW,
    XF86DOS,
    XF86ScreenSaver,
    XF86RotateWindows,
    XF86TaskPane,
    XF86MyComputer,
    XF86Back,
    XF86Forward,
    XF86AudioNext,
    XF86AudioPrev,
    XF86AudioStop,
    XF86Eject,
    XF86AudioRecord,
    XF86AudioRewind,
    XF86Phone,
    XF86HomePage,
    XF86Reload,
    XF86ScrollUp,
    XF86ScrollDown,
    parenleft,
    parenright,
    XF86New,
    Redo,
    XF86Tools,
    XF86Launch5,
    XF86Launch6,
    XF86Launch7,
    XF86Launch8,
    XF86Launch9,
    ISO_Level5_Shift,
    Alt_L,
    Meta_L,
    XF86AudioPlay,
    XF86AudioPause,
    XF86Launch3,
    XF86Launch4,
    XF86LaunchB,
    XF86Suspend,
    XF86Close,
    XF86AudioForward,
    Print,
    XF86WebCam,
    XF86AudioPreset,
    XF86Mail,
    XF86Search,
    XF86Go,
    XF86Finance,
    XF86Shop,
    Cancel,
    XF86MonBrightnessDown,
    XF86MonBrightnessUp,
    XF86AudioMedia,
    XF86Display,
    XF86KbdLightOnOff,
    XF86KbdBrightnessDown,
    XF86KbdBrightnessUp,
    XF86Send,
    XF86Reply,
    XF86MailForward,
    XF86Save,
    XF86Documents,
    XF86Battery,
    XF86Bluetooth,
    XF86WLAN,
    XF86UWB,
    XF86Next_VMode,
    XF86Prev_VMode,
    XF86MonBrightnessCycle,
    XF86BrightnessAuto,
    XF86DisplayOff,
    XF86WWAN,
    XF86RFKill,
    XF86AudioMicMute,
    XF86Info,
    XF86Favorites,
    XF86CycleAngle,
    XF86FullScreen,
    XF86Keyboard,
    XF86AspectRatio,
    XF86DVD,
    XF86Audio,
    XF86Video,
    XF86Calendar,
    XF86ChannelUp,
    XF86ChannelDown,
    XF86AudioRandomPlay,
    XF86Break,
    XF86VideoPhone,
    XF86Game,
    XF86ZoomIn,
    XF86ZoomOut,
    XF86ZoomReset,
    XF86Word,
    XF86Editor,
    XF86Excel,
    XF86GraphicsEditor,
    XF86Presentation,
    XF86Database,
    XF86News,
    XF86Voicemail,
    XF86Addressbook,
    XF86Messenger,
    XF86DisplayToggle,
    XF86SpellCheck,
    XF86LogOff,
    dollar,
    EuroSign,
    XF86FrameBack,
    XF86FrameForward,
    XF86ContextMenu,
    XF86MediaRepeat,
    XF8610ChannelsUp,
    XF8610ChannelsDown,
    XF86Images,
    XF86NotificationCenter,
    XF86PickupPhone,
    XF86HangupPhone,
    XF86Fn,
    XF86Fn_Esc,
    XF86FnRightShift,
    braille_dot_1,
    braille_dot_2,
    braille_dot_3,
    braille_dot_4,
    braille_dot_5,
    braille_dot_6,
    braille_dot_7,
    braille_dot_8,
    braille_dot_9,
    XF86Numeric0,
    XF86Numeric1,
    XF86Numeric2,
    XF86Numeric3,
    XF86Numeric4,
    XF86Numeric5,
    XF86Numeric6,
    XF86Numeric7,
    XF86Numeric8,
    XF86Numeric9,
    XF86NumericStar,
    XF86NumericPound,
    XF86NumericA,
    XF86NumericB,
    XF86NumericC,
    XF86NumericD,
    XF86CameraFocus,
    XF86WPSButton,
    XF86TouchpadToggle,
    XF86TouchpadOn,
    XF86TouchpadOff,
    XF86CameraZoomIn,
    XF86CameraZoomOut,
    XF86CameraUp,
    XF86CameraDown,
    XF86CameraLeft,
    XF86CameraRight,
    XF86AttendantOn,
    XF86AttendantOff,
    XF86AttendantToggle,
    XF86LightsToggle,
    XF86ALSToggle,
    XF86RotationLockToggle,
    XF86Buttonconfig,
    XF86Taskmanager,
    XF86Journal,
    XF86ControlPanel,
    XF86AppSelect,
    XF86Screensaver,
    XF86VoiceCommand,
    XF86Assistant,
    ISO_Next_Group,
    XF86EmojiPicker,
    XF86Dictate,
    XF86CameraAccessEnable,
    XF86CameraAccessDisable,
    XF86CameraAccessToggle,
    XF86BrightnessMin,
    XF86BrightnessMax,
    XF86KbdInputAssistPrev,
    XF86KbdInputAssistNext,
    XF86KbdInputAssistAccept,
    XF86KbdInputAssistCancel,
    XF86RightUp,
    XF86RightDown,
    XF86LeftUp,
    XF86LeftDown,
    XF86RootMenu,
    XF86MediaTopMenu,
    XF86Numeric11,
    XF86Numeric12,
    XF86AudioDesc,
    XF863DMode,
    XF86NextFavorite,
    XF86StopRecord,
    XF86PauseRecord,
    XF86VOD,
    XF86Unmute,
    XF86FastReverse,
    XF86SlowReverse,
    XF86Data,
    XF86OnScreenKeyboard,
    XF86PrivacyScreenToggle,
    XF86SelectiveScreenshot,
    XF86NextElement,
    XF86PreviousElement,
    XF86AutopilotEngageToggle,
    XF86MarkWaypoint,
    XF86Sos,
    XF86NavChart,
    XF86FishingChart,
    XF86SingleRangeRadar,
    XF86DualRangeRadar,
    XF86RadarOverlay,
    XF86TraditionalSonar,
    XF86ClearvuSonar,
    XF86SidevuSonar,
    XF86NavInfo,
    XF86BrightnessAdjust,
    XF86Macro1,
    XF86Macro2,
    XF86Macro3,
    XF86Macro4,
    XF86Macro5,
    XF86Macro6,
    XF86Macro7,
    XF86Macro8,
    XF86Macro9,
    XF86Macro10,
    XF86Macro11,
    XF86Macro12,
    XF86Macro13,
    XF86Macro14,
    XF86Macro15,
    XF86Macro16,
    XF86Macro17,
    XF86Macro18,
    XF86Macro19,
    XF86Macro20,
    XF86Macro21,
    XF86Macro22,
    XF86Macro23,
    XF86Macro24,
    XF86Macro25,
    XF86Macro26,
    XF86Macro27,
    XF86Macro28,
    XF86Macro29,
    XF86Macro30,
    XF86MacroRecordStart,
    XF86MacroRecordStop,
    XF86MacroPresetCycle,
    XF86MacroPreset1,
    XF86MacroPreset2,
    XF86MacroPreset3,
    XF86KbdLcdMenu1,
    XF86KbdLcdMenu2,
    XF86KbdLcdMenu3,
    XF86KbdLcdMenu4,
    XF86KbdLcdMenu5,

    pub const Count = std.meta.fields(@This()).len;
    pub const State = protocols.wayland.Keyboard.KeyState;
    // pub const State = enum(u32) {
    //     released = 0,
    //     pressed = 1,
    //     repeated = 2,
    // };
};

pub const Mouse = struct {
    pub const Button = enum(u32) {
        left = 0,
        right = 1,
        middle = 2,

        pub const Count = std.meta.fields(@This()).len;
        pub const State = enum(u32) {
            released = 0,
            pressed = 1,
        };
    };
};
